name: Build and Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clone public repository
      uses: actions/checkout@v3
      with:
        repository: dewiktor2/cat-management-public
        path: cat-management-public

    - name: Clone private repository
      env:
        PRIVATE_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
      run: |
        git clone https://x-access-token:${PRIVATE_TOKEN}@github.com/dewiktor2/cat-management-private.git cat-management-private

  
    - name: Debug repositories
      run: |
        ls -la cat-management-public
        ls -la cat-management-private

    - name: Build and Run with Docker Compose
      working-directory: ./cat-management-private
      run: docker-compose up --build -d
