name: Build and Deploy with Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Clone the public repository
    - name: Clone public repository
      uses: actions/checkout@v3
      with:
        repository: dewiktor2/cat-management-public
        path: cat-management-public

    # Clone the private repository using Personal Access Token (PAT)
    - name: Clone private repository
      env:
        PRIVATE_TOKEN: ${{ secrets.PRIVATE_TOKEN }}
      run: |
        git clone https://x-access-token:${PRIVATE_TOKEN}@github.com/dewiktor2/cat-management-private.git cat-management-private

    # Install Docker Compose
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    # Debug repositories
    - name: Debug repositories
      run: |
        ls -la cat-management-public
        ls -la cat-management-private

    # Build and start the application using Docker Compose
    - name: Build and Run with Docker Compose
      working-directory: ./cat-management-private
      run: docker-compose up --build -d

    # Update build status file
    - name: Update build status file
      run: |
        echo "Build Status: SUCCESS" > build-status.txt
      working-directory: ./cat-management-public

    # Commit and push build status to public repository
    - name: Commit and push build status
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add build-status.txt
        git commit -m "Update build status"
        git push https://x-access-token:${GITHUB_TOKEN}@github.com/dewiktor2/cat-management-public.git HEAD:main
      working-directory: ./cat-management-public

    # Stop and remove Docker containers after execution (optional)
    - name: Stop Docker Compose
      working-directory: ./cat-management-private
      run: docker-compose down
